language: r
cache: packages
sudo: false

r_packages:
  - covr
bioc_packages:
  - Biobase
  - BiocGenerics
  - lumi
  - limma
  - preprocessCore
  - AnnotationDbi
  - lumiHumanAll.db
  - genefilter
  - illuminaHumanv4.db
after_success:
  - Rscript -e 'library(covr); codecov()'
